### ISSUE TITLE
[BUG] Consecutive executions of the same script yield errors.

### ISSUE THREAD

**Issue by alexsisu** [BlazingDB/blazingsql#466] opened 2020-03-19 15:00 UTC
**Describe the bug**
Running twice this code: https://gist.github.com/alexsisu/0eb74f0298f55f64046acbe56833a4ae
First time it works.
Second time it crashes with:
```
(blazingsql) root@ip-172-31-3-117:/mnt/conduit/blazing_poc/standalone_benchmark# python perf03_parquet.py
listening: tcp://*:24031
Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:261)
Aborted (core dumped)
```

This happened twice in a series of repeted tests.
I was able to reproduce it only twice.
The dataset can be found here:
https://www.dropbox.com/s/aeqbb0fsv4klvsc/file_conduitbugbash_taxi_2019_ORQXQ2K7GIYDCOI_snappy_parquet.tar.gz?dl=0

**Environment**

Latest blazingsql-nightly image: `docker pull blazingdb/blazingsql-nightly:cuda10.1-py3.7`

**Comment by williamBlazing** [comment] 2020-03-19 15:55
Hello @alexsisu Could you please provide us with the RAL.x.log files. Those would be very helpful here

**Comment by rommelDB** [comment] 2020-03-23 16:57
I could not reproduce this error. I'm going to close it. Please feel free to re-open it if still experiencing the problem.

**Closed by rommelDB** 2020-03-23 16:57 UTC
Labels: bug
