### ISSUE TITLE
[BUG] Adding header argument throwing exception

### ISSUE THREAD

**Issue by bsuryadevara** [BlazingDB/blazingsql#606] opened 2020-05-05 02:53 UTC
**Describe the bug**
Error while creating the table with argument header=0

**Steps/Code to reproduce bug**

Please find the attached screenshots for the same

**Expected behavior**
A clear and concise description of what you expected to happen

**Environment details**
Used latest version of balzingsql image from https://hub.docker.com/r/blazingdb/blazingsql

**Comment by bsuryadevara** [comment] 2020-05-05 02:55
![Screen Shot 2020-05-04 at 10 39 23 AM](https://user-images.githubusercontent.com/4812413/81031443-e42ef800-8e51-11ea-90ed-b55bea6c1a92.png)

**Comment by williamBlazing** [comment] 2020-05-06 22:00
Resolved in branch-0.14. 
Please re-open if the issue is not resolved

**Closed by williamBlazing** 2020-05-06 22:00 UTC
Labels: bug
