### ISSUE TITLE
[BUG] Coalesce can throw calcite parsing error

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#794] opened 2020-06-15 14:26 UTC
q= f'''
WITH
locale as (
SELECT
_col0 as d_id
FROM
depot_us_wm_store_scanv_hrly_fin_locale_dim
),
item as (
SELECT
_col0 as item_id,
_col1,
_col2 as model_id,
_col3 as d_id,
_col4,
_col5,
_col8,
_col9,
_col10
FROM
table_a
),
thingy_place as (
SELECT * FROM(
SELECT
locale.d_id as d_id,
CASE WHEN item.model_id IS NOT NULL THEN item.model_id ELSE -999 END as model_id
FROM
locale as locale
LEFT JOIN item AS item ON locale.d_id = item.d_id
WHERE
model_id < 0
)
),
join_12 AS (
SELECT
COALESCE(depot.palce_id,-999) AS palce_id,
'US' AS country,
COALESCE(depot.trans_id,-999) AS trans_id,
depot.trans_type AS trans_type,
COALESCE(depot.moment_type,-999) AS moment_type,
COALESCE(depot.moment_subtype,-999) AS moment_subtype,
COALESCE(depot.rpt_cd, '') AS RPT_CD,
COALESCE(thingy_place.d_id,-999) AS d_id,
thingy_place.model_id,
COALESCE(thingy_place.d_id,-999) AS locale_RING_NBR
FROM
(
SELECT
*,
CASE when trans_type = 1 then trans_id
ELSE CAST(trans_id/10000000 as INTEGER)
END as join_trans_id
FROM
{table}
WHERE
trans_type in (1, 2)
) as depot
LEFT JOIN (
SELECT * from thingy_place
) AS thingy_place
ON join_trans_id = thingy_place.d_id
)
"""
    print(bc.explain(f'{q}SELECT * FROM join_12'))
ERROR:
SQL Parsing Error
Field ordinal 1 is invalid for  type 'RecordType(SMALLINT palce_id)'

**Comment by Christian8491** [comment] 2020-06-23 22:30
I can't reproduce this issue. Maybe some context will help. As tables' schema

**Comment by williamBlazing** [comment] 2020-06-30 18:25
Issue was resolved by some recent PR

**Closed by williamBlazing** 2020-06-30 18:25 UTC
Labels: bug
