### ISSUE TITLE
[BUG] Valid but unimplemented Calcite query hangs kernel and does not respond to interrupt signal

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1136] opened 2020-11-10 15:52 UTC
If I write a valid Calcite SQL query that contains an operation that is not implemented, it appears that the kernel will hang and that an interrupt signal will not stop the apparent hang. In the 2020-11-09 nightlies:

As an example, the following hangs the kernel, but succeeds with `UNION ALL` instead of `UNION`.

```python
from blazingsql import BlazingContext
import cudf
from dask.datasets import timeseries
import pandas as pd

bc = BlazingContext()

df = pd.DataFrame({
    "a": ["Adele", "James"],
    "b": [10, 3]
})

bc.create_table("df", df)
bc.create_table("df2", df)

query = """
SELECT
    *
FROM df
UNION
SELECT
    *
FROM df2
"""
​
bc.explain(query)
# bc.sql(query) # hangs the kernel, and is uninterruptible
'LogicalUnion(all=[false])\n  LogicalTableScan(table=[[main, df]])\n  LogicalTableScan(table=[[main, df2]])\n'
```

Perhaps this RAL_EXPECTS should be throwing but isn't? https://github.com/BlazingDB/blazingsql/blob/4af4683e26a37ca593ba9ee722bfeff6a3b3deab/engine/src/execution_graph/logic_controllers/BatchUnionProcessing.h#L35

Some exceptions are being caught, but appear to still cause an uninterruptible hang.

```python
query = """
SELECT
    UPPER(a)
FROM df
"""
​
print(bc.explain(query))
bc.sql(query)
LogicalProject(EXPR$0=[UPPER($0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[EXPR$0]])

UPPER is not a valid operator.
[07:50:01.673] [error] 1616321269|0|0|In Projection kernel batch 0 for LogicalProject(EXPR$0=[UPPER($0)]). What: Ral failure at: /opt/conda/envs/rapids/conda-bld/blazingsql_1604912264846/work/engine/src/parser/expression_utils.cpp:298: Unsupported operator: UPPER|||||
```

```
conda list | grep blazingsql
blazingsql                0.17.0a         cuda10.2_py37_130    blazingsql-nightly/label/cuda10.2
```

**Comment by Christian8491** [comment] 2020-11-17 00:08
@beckernick could you try again? As many changes to the new comms was merged the hangs should have disappeared. I just tested these queries and what currently I got was a segmentation fault (due to Unsupported operator)

**Comment by beckernick** [comment] 2020-11-17 15:58
Progress 😄 

Ideally, this error would be caught rather than cause a segfault and kill the process.

**Comment by jeanp413** [comment] 2020-11-19 16:22
@beckernick can you test it again with a new conda env and the latest blazingsql package and share your environment info
it seems it's environment related because some of us can't reproduce the issue and some can (me in this case)

**Comment by beckernick** [comment] 2020-11-19 16:54
In a fresh nightly from 5 minutes ago, this hangs:


```
python
Python 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:45:15)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blazingsql import BlazingContext
>>> import cudf
>>> from dask.datasets import timeseries
>>> import pandas as pd
>>>
>>> bc = BlazingContext()
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201119/lib/blazingsql-algebra.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
BlazingContext ready
>>>
>>> df = pd.DataFrame({
...     "a": ["Adele", "James"],
...     "b": [10, 3]
... })
>>>
>>> bc.create_table("df", df)
>>> bc.create_table("df2", df)
>>>
>>> query = """
... SELECT
...     *
... FROM df
... UNION
... SELECT
...     *
... FROM df2
... """
>>>
>>> bc.explain(query)
'LogicalUnion(all=[false])\n  LogicalTableScan(table=[[main, df]])\n  LogicalTableScan(table=[[main, df2]])\n'
>>> bc.sql(query)
# hangs
```

```
conda list | grep "rapids\|dask\|distrib\|blazingsql"
# packages in environment at /raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201119:
blazingsql                0.17.0a         cuda10.2_py37_55    blazingsql-nightly/label/cuda10.2
cudf                      0.17.0a201119   cuda_10.2_py37_g1a80df96c4_285    rapidsai-nightly
cuml                      0.17.0a201119   cuda10.2_py37_gd30edd9f5_127    rapidsai-nightly
dask                      2.30.0+65.g3c64a880          pypi_0    pypi
dask-cuda                 0.17.0a201119           py37_42    rapidsai-nightly
dask-cudf                 0.17.0a201119   py37_g1a80df96c4_285    rapidsai-nightly
distributed               2.31.0.dev0+39.g7e2fb2ff          pypi_0    pypi
faiss-proc                1.0.0                      cuda    rapidsai-nightly
libcudf                   0.17.0a201119   cuda10.2_g1a80df96c4_285    rapidsai-nightly
libcuml                   0.17.0a201119   cuda10.2_gb205e8fd0_128    rapidsai-nightly
libcumlprims              0.17.0a201030   cuda10.2_g1fa28a5_8    rapidsai-nightly
librmm                    0.17.0a201106   cuda10.2_gb1ac445_43    rapidsai-nightly
rmm                       0.17.0a201106   cuda_10.2_py37_gb1ac445_43    rapidsai-nightly
ucx                       1.8.1+g6b29558       cuda10.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.17.0a201119   py37_g6b29558_20    rapidsai-nightly
```

**Closed** 2020-11-20 21:23 UTC
Labels: bug
