### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: CatalogColumnDataType

### ISSUE THREAD

**Issue by RXY3832** [BlazingDB/blazingsql#183] opened 2019-12-24 17:02 UTC
After installing via:

``
conda install -c blazingsql/label/cuda10.0 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.6 cudatoolkit=10.0
``

I get the following error on import:

``
java.lang.NoClassDefFoundError: com/blazingdb/calcite/catalog/domain/CatalogColumnDataType
``

I followed the recommended install directions. I haven't found away around this issue. I tried the nightly build too, but that gave the same error.

**Comment by williamBlazing** [comment] 2020-01-06 20:51
Can you provide the output of `conda list` from your environment to see what versions you installed

**Comment by jdamiani27** [comment] 2020-01-27 18:40
I have the same issue, but I noticed that it is only occurring for me in a Jupyter Notebook environment (in particular, Jupyter Lab).  I do not run into the issue from a Python or IPython shell when activated in my environment.

Here is my `conda list` output:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
blazingsql                0.11            cuda10.0_py37_2    blazingsql/label/cuda10.0
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bsql-toolchain            0.11                          0    blazingsql
bsql-toolchain-aws-cpp    0.11                          0    blazingsql
bsql-toolchain-gcp-cpp    0.11                          0    blazingsql
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cppzmq                    4.3.0             hc9558a2_1001    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
cudatoolkit               10.0.130                      0    nvidia
cudf                      0.11.0                   py37_0    rapidsai
cudnn                     7.6.0                cuda10.0_0    nvidia
cupy                      6.7.0            py37he57b8b9_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cyrus-sasl                2.1.27               he38ecfd_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.9.2                      py_0    conda-forge
dask-core                 2.9.2                      py_0    conda-forge
dask-cuda                 0.11.0                   py37_0    rapidsai
dask-cudf                 0.11.0                   py37_0    rapidsai
decorator                 4.4.1                      py_0  
distributed               2.9.3                      py_0    conda-forge
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
fastavro                  0.22.9           py37h516909a_0    conda-forge
fastrlock                 0.4             py37he1b5a44_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
future                    0.18.2                   py37_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.4                      243  
ipykernel                 5.1.3            py37h39e3cac_1  
ipython                   7.11.1           py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
jedi                      0.15.2                   py37_0  
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jpype1                    0.7              py37h9de70de_0    conda-forge
jupyter_client            5.3.4                    py37_0  
jupyter_core              4.6.1                    py37_0  
krb5                      1.16.4               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcudf                   0.11.0               cuda10.0_0    rapidsai
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libgpg-error              1.36                 he1b5a44_0    conda-forge
libgsasl                  1.8.0             h19a2143_1004    conda-forge
libhdfs3                  2.3               h311b756_1006    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libntlm                   1.4               h14c3975_1002    conda-forge
libnvstrings              0.11.0               cuda10.0_0    rapidsai
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.11.0               cuda10.0_0    rapidsai
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nccl                      2.4.6.1              cuda10.0_0    nvidia
ncurses                   6.1                  he6710b0_1  
netifaces                 0.10.9          py37h516909a_1000    conda-forge
numba                     0.47.0           py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
nvstrings                 0.11.0                   py37_0    rapidsai
olefile                   0.46                       py_0    conda-forge
openjdk                   8.0.192           h14c3975_1003    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.5.2                      py_0  
partd                     1.1.0                      py_0    conda-forge
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.3.0           py37h00a061d_1000    conda-forge
pip                       19.3.1                   py37_0  
prompt_toolkit            3.0.2                      py_0  
psutil                    5.6.7            py37h516909a_0    conda-forge
ptyprocess                0.6.0                    py37_0  
pyarrow                   0.15.0           py37h8b68381_1    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.5.2                      py_0  
pyhive                    0.6.1                    py37_0  
pynvml                    8.0.4                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0  
pytz                      2019.3                     py_0  
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     18.1.0           py37he6710b0_0  
re2                       2020.01.01           he1b5a44_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_1    conda-forge
rmm                       0.11.0                   py37_0    rapidsai
sasl                      0.2.1           py37he1b5a44_1001    conda-forge
setuptools                44.0.0                   py37_0  
six                       1.13.0                   py37_0  
snappy                    1.1.7             he1b5a44_1003    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlalchemy                1.3.13           py37h516909a_0    conda-forge
sqlite                    3.30.1               h7b6447c_0  
tblib                     1.6.0                      py_0    conda-forge
thrift                    0.11.0          py37he1b5a44_1001    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
thrift_sasl               0.3.0           py37h516909a_1001    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h7b6447c_0  
traitlets                 4.3.3                    py37_0  
uriparser                 0.9.3                he1b5a44_1    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wcwidth                   0.1.7                    py37_0  
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.1                he6710b0_3  
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```

**Comment by williamBlazing** [comment] 2020-01-30 20:56
@RXY3832 We are going to be releasing a new "Stable" build soon. Early next week. In that new release, the building process has changed a little. I would like to request you try again with the new build when its available and if you are still having issues, we can look at it again.

**Comment by sshakeri** [comment] 2020-02-16 20:47
Ran to this issue.  I created a new conda virtual env with these packages (cuda10.1) and it works

```
export conda_env=p3g

conda create --name $conda_env -y

conda activate $conda_env
conda install -c blazingsql-nightly/label/cuda10.1 -c blazingsql-nightly -c rapidsai-nightly -c conda-forge -c defaults blazingsql cudf  dask-cudf  dask-cuda  cudatoolkit ipykernel  python=3.7 -n $conda_env 
```

**Comment by rhyswhitley** [comment] 2020-02-18 00:37
@sshakeri Just tried the above and the error still persists for me.

**Comment by aucahuasi** [comment] 2020-03-13 17:39
@RXY3832 We did a patch in our latest official release. The issue here is that somehow our stack was not properly detecting the java runtime. Please try to install our latest release, and check with 
`echo $JAVA_HOME`
that points to your conda env.

Let's know if the issue is gone! thanks! ;)

cc @rhyswhitley @sshakeri @jdamiani27

**Comment by williamBlazing** [comment] 2020-03-13 18:39
Closing this issue for now. If this is still an issue, please feel free to re-open and we can look into it again

**Closed by williamBlazing** 2020-03-13 18:39 UTC
Labels: bug
