### ISSUE TITLE
[BUG] Cannot call compute() on a query result

### ISSUE THREAD

**Issue by randerzander** [BlazingDB/blazingsql#358] opened 2020-02-05 03:21 UTC
Unable to call `compute()` on a query result. I'd expect to be able to get a cudf DataFrame from this snippet.
```
from blazingsql import BlazingContext
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import pandas as pd
import os

cluster = LocalCUDACluster()
client = Client(cluster)
bc = BlazingContext(dask_client = client, network_interface = 'lo')

# create a test parquet file
df = pd.DataFrame()
df['id'] = [0, 1, 2, 2, 3]
df['val'] = [0, 1, 2, 2, 3]

path = os.getcwd()+'/test.parquet'
df.to_parquet(path)

bc.create_table('test', path)
bc.sql('select * from test').compute()
```

Result:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-a46f05122024> in <module>
----> 1 bc.sql('select * from test').compute()

/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2585                     should_rejoin = False
   2586             try:
-> 2587                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2588             finally:
   2589                 for f in futures.values():

/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1883                 direct=direct,
   1884                 local_worker=local_worker,
-> 1885                 asynchronous=asynchronous,
   1886             )
   1887 

/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    765         else:
    766             return sync(
--> 767                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    768             )
    769 

/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    343     if error[0]:
    344         typ, exc, tb = error[0]
--> 345         raise exc.with_traceback(tb)
    346     else:
    347         return result[0]

/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py in f()
    327             if callback_timeout is not None:
    328                 future = asyncio.wait_for(future, callback_timeout)
--> 329             result[0] = yield future
    330         except Exception as exc:
    331             error[0] = sys.exc_info()

/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1739                             exc = CancelledError(key)
   1740                         else:
-> 1741                             raise exception.with_traceback(traceback)
   1742                         raise exc
   1743                     if errors == "skip":

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in check_meta()
    667     raise ValueError(
    668         "Metadata mismatch found%s.\n\n"
--> 669         "%s" % ((" in `%s`" % funcname if funcname else ""), errmsg)
    670     )
    671 

ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `cudf.core.dataframe.DataFrame`
+--------+-------+----------+
| Column | Found | Expected |
+--------+-------+----------+
| id     | int64 | -        |
| val    | int64 | -        |
+--------+-------+----------+
```

Possibly relatedly, `.head()` on the result returns no data:
```
bc.sql('select * from test').head()

0
1
2
3
4
```

**Comment by williamBlazing** [comment] 2020-02-13 18:47
For BlazingSQL Devs.
This issue is likely related to the fact that in a distributed context, here there is only one file and the engine is only doing a project. So all but one of the workers are returning nothing, but they should return a dataframe with columns, but no rows.

**Comment by aucahuasi** [comment] 2020-02-13 22:10
Hi @randerzander same with this one: i cannot reproduce it

It seems is working fine with the latest changes from cudf and blazingsql

```
from blazingsql import BlazingContext
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import pandas as pd
import os

def main():
    cluster = LocalCUDACluster()
    client = Client(cluster)
    bc = BlazingContext(dask_client = client, network_interface = 'lo')

    # create a test parquet file
    df = pd.DataFrame()
    df['id'] = [0, 1, 2, 2, 3]
    df['val'] = [0, 1, 2, 2, 3]

    path = os.getcwd()+'/test.parquet'
    df.to_parquet(path)

    bc.create_table('test', path)
    result = bc.sql('select * from test').compute()
    print(result)

if __name__ == "__main__":
    main()

```

printing:
```
   id  val
0   0    0
1   1    1
2   2    2
3   2    2
4   3    3
```

**Comment by aucahuasi** [comment] 2020-02-14 18:25
Hi @randerzander we are waiting for this issue https://github.com/rapidsai/cudf/issues/4152 once the PR gets merged we have ready the fix fir your issue!

**Comment by aucahuasi** [comment] 2020-02-15 00:20
Hi @randerzander this PR https://github.com/BlazingDB/blazingsql/pull/412 also fix this issue. I'm gonna close this issue, please try again! Thanks!

**Closed by aucahuasi** 2020-02-15 00:20 UTC
Labels: bug
